name: cmcc-rxn
channels:
  - rdkit
  - defaults
  - pytorch
  - nvidia
dependencies:
  - "python=3.10"
  - "matplotlib"
  - "ipykernel"
  - "pybind11"
  - "pip"
  - pip:
    - "torch"
    - "ase"
    - "rdkit"
    - "mccoygroup-mcutils"
